### ISSUE TITLE
Usage of Inventory.isFull() drops fps to a fraction

### ISSUE THREAD

**Issue by Semajian** [RSKraken/KrakenAPI#2]
I don't think everybody has this issue but saw it discussed elsewhere. Even in a completely clean script using Inventory.isFull grinds my entire client to a halt, printing maybe a frame every few seconds

**Comment by Semajian** [comment]
Have done a little more testing - it seems that the issue lies in getItems() - if I have an unbroken  consecutive inventory of items, I.E no gaps in index order the getItems() call works - but as soon as I have an item AFTER an empty slot I.E second inventory slot has item first doesn't, all inventory is full apart from index 23 , all inventory is full about from first slot, the issues start. Empty inventory works fine too

**Comment by titandino** [comment]
Yep. This is definitely how to reproduce it. Found that out today when my account got a clue scroll at the end of its inventory while converting divine energy.

**Comment by RSKraken** [comment]
I'm investigating. Will report back.

**Comment by RSKraken** [comment]
I'm on a roll with JVM memory corruptions. Patch is deployed momentarily. Thank you for reporting.
